### ISSUE TITLE
Installation the driver in docker container with pypy

### ISSUE THREAD

**Issue by vmarunov** [autumnjolitz/aerospike#2]
Hi!

I'm tryed install this driver in docker container with pypy.
My Dockerfile:
```
FROM pypy:2-slim

RUN apt-get update && apt-get install -y libc6-dev libssl-dev wget git clang build-essential

ENV LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

RUN mkdir install && \
    cd /install && \
    wget 'https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz' && \
    tar xvf libevent-2.0.21-stable.tar.gz && \
    cd libevent-2.0.21-stable && \
    ./configure PREFIX=/usr && \
    make && \
    make install

ADD . /install/
RUN cd /install/citrusleaf_client_libevent2_2.1.44 && \
    make

RUN pip install --no-cache-dir six git+https://github.com/benjolitz/aerospike.git

ENTRYPOINT sh
```

citrusleaf_client_libevent2_2.1.44 - pathed with https://gist.github.com/benjolitz/bbdb48ed33eb50711f23

Examples from citrusleaf_client_libevent2_2.1.44 is work into container:
```
# cd /install/citrusleaf_client_libevent2_2.1.44/example
# ./example -h 192.168.56.101
host:                192.168.56.101
port:                3000
namespace:           test
set name:            test-set
transaction timeout: 200 msec
found 1 cluster node
completed info query
completed phase 1
completed phase 2
completed phase 3
completed phase 4
completed phase 5
completed phase 6
completed phase 7
completed phase 8
example completed all 8 database transactions
example is done
```

But in pypy connect do not work:
```
# aerospike-cli --host 192.168.56.101
Traceback (most recent call last):
  File "/usr/local/bin/aerospike-cli", line 11, in <module>
    load_entry_point('aerospike==0.0.1', 'console_scripts', 'aerospike-cli')()
  File "/usr/local/site-packages/aerospike/__init__.py", line 77, in setup_cli
    client = get_client()
  File "/usr/local/site-packages/aerospike/__init__.py", line 49, in get_client
    cls = load_library()
  File "/usr/local/site-packages/aerospike/api.py", line 26, in load_library
    raise ImportError("Unable to load aerospike libraries!")
ImportError: Unable to load aerospike libraries!
```

```
# pypy
Python 2.7.13 (fa3249d55d15, Mar 19 2017, 20:21:48)
[PyPy 5.7.0 with GCC 6.2.0 20160901] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import aerospike
>>>> client = aerospike.get_client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/site-packages/aerospike/__init__.py", line 49, in get_client
    cls = load_library()
  File "/usr/local/site-packages/aerospike/api.py", line 26, in load_library
    raise ImportError("Unable to load aerospike libraries!")
ImportError: Unable to load aerospike libraries!
```

Have you any idea?

Thanks.

**Comment by vmarunov** [comment]
I'm tryed find libraries manually:

```
>>>> from ctypes.util import find_library
>>>> find_library('aerospike')
>>>> find_library('ev2citrusleaf-2.0')
>>>> find_library('event')
'libevent-2.0.so.5'
>>>> find_library('event-2.0')
>>>> find_library('citrusleaf-2.0')
```

Why libraries not found?
